name: mongo-sharding-repl

services:
  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mongos_router:
        condition: service_started
    environment:
      MONGODB_URL: "mongodb://mongos_router:27017"
      MONGODB_DATABASE_NAME: "somedb"
    restart: on-failure

  mongos_router:
    container_name: mongos_router
    image: mongo:6
    command: mongos --configdb cfg_replset/config_server_1:27019,config_server_2:27019,config_server_3:27019 --bind_ip_all
    ports:
      - "27017:27017"
    depends_on:
      config_server_1:
        condition: service_started
      config_server_2:
        condition: service_started
      config_server_3:
        condition: service_started
      shard1_1:
        condition: service_started
      shard1_2:
        condition: service_started
      shard1_3:
        condition: service_started
      shard2_1:
        condition: service_started
      shard2_2:
        condition: service_started
      shard2_3:
        condition: service_started

  config_server_1:
    container_name: config_server_1
    image: mongo:6
    command: mongod --configsvr --replSet cfg_replset --port 27019
    volumes:
      - config_data_1:/data/configdb

  config_server_2:
    container_name: config_server_2
    image: mongo:6
    command: mongod --configsvr --replSet cfg_replset --port 27019
    volumes:
      - config_data_2:/data/configdb

  config_server_3:
    container_name: config_server_3
    image: mongo:6
    command: mongod --configsvr --replSet cfg_replset --port 27019
    volumes:
      - config_data_3:/data/configdb

  shard1_1:
    container_name: shard1_1
    image: mongo:6
    command: mongod --shardsvr --replSet shard1 --port 27018
    ports:
      - "27018:27018"
    volumes:
      - shard1_1_data:/data/db

  shard1_2:
    container_name: shard1_2
    image: mongo:6
    command: mongod --shardsvr --replSet shard1 --port 27018
    volumes:
      - shard1_2_data:/data/db

  shard1_3:
    container_name: shard1_3
    image: mongo:6
    command: mongod --shardsvr --replSet shard1 --port 27018
    volumes:
      - shard1_3_data:/data/db

  shard2_1:
    container_name: shard2_1
    image: mongo:6
    command: mongod --shardsvr --replSet shard2 --port 27019
    ports:
      - "27019:27019"
    volumes:
      - shard2_1_data:/data/db

  shard2_2:
    container_name: shard2_2
    image: mongo:6
    command: mongod --shardsvr --replSet shard2 --port 27019
    volumes:
      - shard2_2_data:/data/db

  shard2_3:
    container_name: shard2_3
    image: mongo:6
    command: mongod --shardsvr --replSet shard2 --port 27019
    volumes:
      - shard2_3_data:/data/db

  mongodb_init:
    container_name: mongodb_init
    image: mongo:6
    depends_on:
      config_server_1:
        condition: service_started
      config_server_2:
        condition: service_started
      config_server_3:
        condition: service_started
      shard1_1:
        condition: service_started
      shard1_2:
        condition: service_started
      shard1_3:
        condition: service_started
      shard2_1:
        condition: service_started
      shard2_2:
        condition: service_started
      shard2_3:
        condition: service_started
      mongos_router:
        condition: service_started
    volumes:
      - ./scripts/mongo-init.sh:/scripts/mongo-init.sh
    entrypoint: ["/bin/sh", "/scripts/mongo-init.sh"]

volumes:
  config_data_1:
  config_data_2:
  config_data_3:
  shard1_1_data:
  shard1_2_data:
  shard1_3_data:
  shard2_1_data:
  shard2_2_data:
  shard2_3_data:
